version: "1.0"

services:
  postgres:
    image: postgres:16.1
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=checkbox_tht
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      common:
        aliases:
          - postgresql
  golang:
    image: tht-cai-be
    restart: no
    ports:
      - "3003:3003"
    networks:
      - common
volumes:
  pgdata:
networks:
  common:
