// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package checkbox_tht

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	NameSearch  interface{}        `json:"name_search"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	IsDone      pgtype.Timestamptz `json:"is_done"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
