### GET request paginated tasks
GET http://localhost:3000

### POST create a task
POST http://localhost:3000
Content-Type: application/json

{
    "name": "Buying office supplies before stopping at office",
    "description": "Description 2",
    "due_date": "2021-12-31T10:00:00Z"
}

### PUT update a task
PUT http://localhost:3000/36
Content-Type: application/json

{
  "name": "Updating spreadsheet before the meeting",
  "description": "Nulla aliqua velit mollit laborum non duis nostrud.",
  "due_date": "2021-12-31T10:00:00Z"
}

### POST set task as done
POST http://localhost:3000/36/toggle

### DELETE remove a task
DELETE http://localhost:3000/44
